# Generated by Django 5.2 on 2025-04-23 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Use the format (99) 99999-9999.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number. Use the format (99) 99999-9999.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')])),
                ('alias', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('JL', 'Liga da Justiça'), ('A', 'Os Vingadores')], default='JL', help_text='Choose your group.', max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
