# Generated by Django 5.2 on 2025-04-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gamer',
            new_name='Player',
        ),
    ]
