# Generated by Django 5.2 on 2025-04-23 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_gamer_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='group',
            field=models.CharField(choices=[('JL', 'Liga da Justiça'), ('A', 'Os Vingadores')], default='JL', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number. Use the format (99) 99999-9999.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
    ]
